name: read file

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fileread:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Run npm commands
        run: |
          npm install
          npm run build

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: todo-app-build
          path: build/
