name: pipeline
on:
  workflow_dispatch:
    inputs:
      environment:
        description: select env
        required: true
        default: dev
        type: chose
        options:
          - dev
          - prod
permissions:
  contents: read
jobs:
  hello:
    runs-on: self-hosted
    steps: 
      - name: Checkout-file
        uses: actions/checkout@v4
      - name: Read-file
        run: cat ./src/App.js