name: Hello World
on: workflow_dispatch
jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: hello-step
        run: |
          echo "JAI JAGNNATH"
          echo "JAI RADHA MAA"
  TELLO:
    runs-on: self-hosted
    needs: hello
    steps:
      - name: test
        run: echo "my repo variable: ${{ var.test }}"
