name: read file

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  fileread:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Azure
        run: |
          az account show
          az group list --output table

      - name: Install Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Run npm commands
        run: |
          npm install
          npm run build

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: todo-app-build
          path: build/
