name:
on:
  workflow_dispatch:
    inputs:
      environment:
        description: select env
        required: true
        default: dev
        type: choice
        options:
          -dev
          -prod
jobs:
  input-demo:
    runs-on: self-hosted
    steps:
      - name: deploy
        run: echo " deploy"
