name: test pipeline
on:
  workflow_dispatch:
    inputs:
      environment:
        description: chose environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod
env:
  APP_ENV: "dev"
jobs:
  hello:
    outputs:
      version: ${{ steps.step2.outputs.version }}
    runs-on: self-hosted
    steps:
      - name: hello-step
        run: echo "JAI JAGNNATH"
      - name: variable check
        id: step2
        run: |
          echo "${{ github.actor }}"
          echo "version=0.0.4" >> $GITHUB_OUTPUT
      - name: code Checkout
        uses: actions/checkout@v4
      - name: print environment
        run: echo "current env is , ${{inputs.environment}}"
      - name: hello-step
        run: |
          echo "version is, ${{ steps.step2.outputs.version }}" 
          echo "$APP_ENV $GITHUB_OUTPUT"

      - name: EVENT Checkout
        if: github.event_name == 'push'
        run: echo "event is ${{ github.event_name }}"
      - name: install docker
        run: docker --version
      - name: EVENT test
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "event is ${{ github.event_name }}"
          docker images
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: version
        run: |
          echo " current version is, ${{ needs.hello.outputs.version}}"
          echo " post version is, $GITHUB_OUTPUT"
    
        

       