name: test pipeline
on:
  workflow_dispatch:
    inputs:
      environment:
        description: chose environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod
env:
  APP_ENV: "dev"
jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: hello-step
        run: echo "JAI JAGNNATH"
      - name: variable check
        run: echo "${{ github.actor }}"
      - name: code Checkout
        uses: actions/checkout@v4
      - name: print environment
        run: echo "current env is , ${{inputs.environment}}"
      - name: hello-step
        run: echo "$APP_ENV"
       